- hosts: all
  tasks:
    - name: install packages
      yum: name="{{item}}" state=present
      with_items:
        - vim
        - docker
        - git
        - tmux

    - name: docker storage config
      template: src=docker-storage-setup dest=/etc/sysconfig/
      register: storage_config

    - name: run docker-storage-setup
      shell: docker-storage-setup
      when: storage_config.changed

    - name: start docker
      service: name=docker state=started enabled=yes

    - name: clone repository
      git:
        repo: https://github.com/tomkukral/kube-demo.git
        dest: /root/kube-demo/
        version: master
    

